### ISSUE TITLE
Who & Why

### ISSUE THREAD

**Issue by shahbaz17** [shahbaz17/theindianwave#1]
Write about it. #1

**Comment by imox2** [comment]
**Who are we?**
Well, our name is **The Indian wave** and what we do is serve soup to you on demand. Only our soup is a bit different, we all html,css and javascript into our soup. The soup we create is also knowns as a website. So if you are in need of soup, the new soup shop in town ( we,we,we ) deserve at least a chance.

**Why?**
See amazing feature, wow feature etc. Merge them.
