### ISSUE TITLE
An amazing feature

### ISSUE THREAD

**Issue by shahbaz17** [shahbaz17/theindianwave#5]

**Comment by imox2** [comment]
You always inherit the mistakes you made, the bugs you created. So after the project is completed, we provide free 6 months/1 year maintenance with it. We believe mistakes are envitable but recognizing your mistake and correcting is heavenly. Don't ever think delivering a project means the relationship you and we have end. 

_Now if you did not understand much of above paragraph, let me summarise it for you in two words_: **Free maintenance**.
